---
title: "My CV"
---

Here you can find all of my experiences. Some of these sections may not be on my CV due to page constraints.

This page was last updated October 2025.

### Profile

I'm an aspiring psychologist with interests in language, mathematical cognition and where they intersect. I aim to use quantitative methods where possible but I'm not afraid of using qualitative methods as well. I've had experience in charity work and hands-on research experience.

---

### Education

**University of Bath**  
_BSc(Hons) Psychology with work placement_  
Sept 2024 -- Present  

- First year grade average: 70
- Modules taken:
  - Mind, Brain and Behaviour (87%)
  - Psychology Research Methods and Design 1 (73%)
    - Received a mark of **80%** on my Quantitative Report 2, demonstrating ability to conduct novel research and present it effectively
  - Applying Psychology (68%)
  - Psychology of Wellbeing (79%)

**Queen Ethelburga's Collegiate**  
_A Levels_  
Sept 2022 -- June 2024

- A Level grades: A\*A\*AB
- In Mathematics, Law, Economics and Psychology

---

### Work Experience

**Research Apprentice**  
_University of Bath, Department of Psychology_  
Nov 2024 -- June 2025

- Assisted with a systematic review on the relationship between alexithymia and parenting behaviour,
improving my skill to filter irrelevant data.

- Engaged in transcription of interviews to validate a screening tool for adults with developmental language disorder, promoting welfare in the community and familarity with Jeffersonian transcription.

- Operated eye-tracking equipment in a laboratory setting.

**Various roles**  
_[Hong Kong Student Association (UK)](https://www.hksacic.co.uk/)_  
Aug 2024 -- Present

- I've been engaged in various roles in this organisation. Prominents ones are my role as _Youth Development Officer_ (2024-25) and _Mentorship programme operations team member_ (2024-26).
- Youth Development Officer:
  - Authored articles on educational and career choices, improving my public communication skills.
  - Managed a subsidiary committee, building on my team and project management skills.
  - **Lead data analyst and coordinator** on research project investigating loneliness in the [Hong Kong BN(O)](https://www.gov.uk/british-national-overseas-bno-visa) community,
enhancing my statistical literacy and criticality by working with a real large dataset.
- Mentorship programme operations team member
  - Took active part in the management of the mentorship programme.
  - Gave academic and career guidance to mentees in their A Level and GCSE studies in the field of psychology as a mentor.
  
**Teaching Intern in Mathematics**  
_Redland Green School, Bristol_  
June 2025 -- July 2025

- Assisted with the delivery of lessons from a wide range of year groups (Years 7–12) by   answering student queries, improving empathetic communication and understanding.
- Delivered a lesson to Year 7 students, enhancing skills to communicate complex ideas.
- Taught small groups of students with SEND needs, boosting awareness of the needs of individuals with specific learning difficulties in a practical context, and how to accommodate these needs.

---

### Projects

**Investigating correlates of loneliness in Hong Kong BN(O) immigrants**  
Sept 2024 -- Present

- Investigated subjective loneliness and its correlates (e.g. cultural integration) in the [Hong Kong BN(O)](https://www.gov.uk/british-national-overseas-bno-visa) immigrant community in the UK.

- Analysed dataset from questionnaire using correlational techniques.

- Proposed suggestions to policymakers regarding what changes could be made to accommodate the community more in the UK.

---

### Volunteering experience

I've also been volunteering as a part of the student community.

**Language Peer Assisted Learning (PAL) Leader**  
_University of Bath Student's Union_  
Feb 2025 -- Present

- Facilitated PAL sessions in English for students whose first language is not English.

- Designed appropriate material for peers to engage in and to understand British culture and the nuances of the English Language, including the introduction of some sociolinguistic concepts such as the myth of the "standard accent".

---

### Skills

- I speak _three_ languages: Cantonese (L1), English (L2) and Mandarin (L3).

- I know how to analyse datasets with R and SPSS.

- I know how to use Microsoft Office and LaTeX.

- I built this website using R Markdown.

---

### Interests

- I have a side interest in linguistics since joining the [UK Linguistics Olympiad](https://www.uklo.org/) in Year 13.
  - I know some elementary linguistics concepts in fields such as phonology, syntax and semantics.

- I also like to learn languages. I've started learning French at university and aim to work towards CEFR B2.

---

<center> **References availaible on request** </center>